name: model-wine-quality
on: 
  push:
    branches:
      - main
      - dvc
jobs:
  run:
    runs-on: [ubuntu-latest]

    

    #container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '12'
      - name: cml_run
        env:
          repo_token: ${{ secrets.TOKEN }}
          MLFLOWURI: ${{ secrets.MLFLOWURI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sudo npm install -g coffee-script
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev \
                        librsvg2-dev libfontconfig-dev
          npm i -g @dvcorg/cml
          npm install -g vega-cli vega-lite
          
          
          # Your ML workflow goes here
          /usr/bin/python3 -m pip install --upgrade pip
          pip install -r req.txt
          python train.py
          
          echo "## Model metrics" > report.md
          
          echo "## Data viz" >> report.md
          bash cml_script/cml_image_publish.sh
          
          cml-send-comment report.md
