name: model-wine-quality
on: 
  push:
    branches:
      - main
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r req.txt
          python train.py
          
          echo "## Model metrics" > report.md
          
          echo "## Data viz" >> report.md
          bash cml_script/cml_image_publish.sh
          
          cml-send-comment report.md
